### ISSUE TITLE
add part 2 - authentication and authorization with stormpath

### ISSUE THREAD

**Issue by connor11528** [connor11528/mean-tutorial#1]
express-stormpath https://github.com/stormpath/express-stormpath

stormpath angularjs https://github.com/stormpath/stormpath-sdk-angularjs

**Comment by connor11528** [comment]
```
$ npm start

> mean-tutorial@1.0.0 start /Users/connorleech/Projects/mean-tutorial
> node server.js

error:  Error: API key ID and secret is required.
    at newError (/Users/connorleech/Projects/mean-tutorial/node_modules/express-stormpath/node_modules/stormpath-config/lib/strategy/ValidateClientConfigStrategy.js:15:14)
    at ValidateClientConfigStrategy.process (/Users/connorleech/Projects/mean-tutorial/node_modules/express-stormpath/node_modules/stormpath-config/lib/strategy/ValidateClientConfigStrategy.js:33:12)
    at fn (/Users/connorleech/Projects/mean-tutorial/node_modules/express-stormpath/node_modules/async/lib/async.js:741:34)
    at /Users/connorleech/Projects/mean-tutorial/node_modules/express-stormpath/node_modules/async/lib/async.js:1208:16
    at /Users/connorleech/Projects/mean-tutorial/node_modules/express-stormpath/node_modules/async/lib/async.js:166:37
    at /Users/connorleech/Projects/mean-tutorial/node_modules/express-stormpath/node_modules/async/lib/async.js:701:43
    at /Users/connorleech/Projects/mean-tutorial/node_modules/express-stormpath/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/Users/connorleech/Projects/mean-tutorial/node_modules/express-stormpath/node_modules/async/lib/async.js:1201:34)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```
